# config.yml includes this file
# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

    # Registered as twig extension (on booting, Twig looks for services tagged as twig.extension)
    app.markdown_extension:
        class: AppBundle\Twig\MarkdownExtension
        tags:
            - { name: twig.extension }
        #arguments: ['@app.markdown_transformer']
        autowire: true

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true